name: Build Project

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Project
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --verbosity normal
